export type Project = {
  id: string;
  title: string;
  tagline: string;
  period: string;       
  tech: string[];       
  repo?: string;         
  live?: string;         
  cover?: string;        
  highlights: string[];  
};

export const projects: Project[] = [
  {
    id: "personal-dashboard",
    title: "Personal Dashboard (WPF)",
    tagline: "Clock, calendar, tasks, and weather widgets with MVVM.",
    period: "2025",
    tech: ["C#", "WPF", "MVVM", "APIs"],
    repo: "https://github.com/xmikolay/PersonalDashboard",
    cover: "/dash.png",
    highlights: [
      "MVVM architecture with commands/services",
      "ICS calendar import (read-only)",
      "Material styling, CSV persistence",
      "Interactive To-Do list"
    ],
  },
  {
    id: "choose-part",
    title: "ChoosePart - PC Part Picker",
    tagline: "App simulating PC part selection and compatibility checks.",
    period: "2025",
    tech: ["C#", "WPF", "SQL", "NUnit"],
    repo: "https://github.com/xmikolay/PC-Parts-Picker-Project",
    cover: "/pcpart.png",
    highlights: [
      "Allows user selection of PC parts",
      "Checks compatibility between selected parts",
      "Uses SQL for data (parts) storage",
      "Unit tests with NUnit"
    ],
  },
  {
    id: "project-300",
    title: "Project 300 (Y3 Project) - Pulse",
    tagline: "Pulse is a web based fitness app which creates personalised workout plans generated by AI.",
    period: "2025-2026",
    tech: ["Next.js", "TypeScript", "REST API", "Tailwind", "Supabase", "Pnpm", "Zod"],
    repo: "https://github.com/Pulse-project-300/atu-project-300",
    cover: "/badges.png",
    highlights: [
      "Group Project - 4 people.",
      "Role: Front-end Developer.",
      "Developed the full-stack achievements and gamification system, implementing Supabase database schema, Express API endpoints, React/Next.js components, and automated badge evaluation logic that awards users for completing workouts and building streaks.",     
    ],
  },
  {
    id: "personal-portfolio",
    title: "Personal Portfolio",
    tagline: "Personal Portfolio website built on Next.js.",
    period: "2025",
    tech: ["Next.js", "React", "Tailwind", "Resend", "Netlify"],
    repo: "https://github.com/xmikolay/portfolio",
    cover: "/portfolio.png",
    highlights: [
      "Shows off selected projects that I am most proud of.",
      "Responsive, modern and sleek UI.",
      "Working mailing service using resend (try it, I'll reply :) ).",
      "My favourite project so far."
    ],
  },
];
